version: '2'
services:
  postgresql:
    container_name: "postgresql"
    image: bitnami/postgresql:10
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/postgresql_data:/bitnami/postgresql
    networks:
      - airflow-compose-network

  redis:
    container_name: "redis"
    image: 'redis:5.0.5'
    ports:
      - "5555:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis_data:/bitnami/redis
    networks:
      - airflow-compose-network
  
  airflow-worker:
    container_name: "airflow-worker"
    image: bitnami/airflow-worker:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./data:/opt/bitnami/data
      - ./src:/opt/bitnami/src
      - ./data/airflow_scheduler_data:/bitnami/airflow_scheduler_data
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./airflow/plugins:/opt/bitnami/airflow/plugins
    networks:
      - airflow-compose-network
    
  airflow-scheduler:
    container_name: "airflow-scheduler"
    image: bitnami/airflow-scheduler:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./data:/opt/bitnami/data
      - ./src:/opt/bitnami/src
      - ./data/airflow_worker_data:/bitnami
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./airflow/plugins:/opt/bitnami/airflow/plugins
    networks:
      - airflow-compose-network

  airflow:
    container_name: "airflow"
    image: bitnami/airflow:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW_LOAD_EXAMPLES=no
    ports:
      - '8080:8080'
    volumes:
      - ./data:/opt/bitnami/data
      - ./airflow/dags:/opt/bitnami/airflow/dags
      - ./airflow/plugins:/opt/bitnami/airflow/plugins
    networks:
      - airflow-compose-network

volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks: 
   airflow-compose-network:
     driver: bridge

