version: '3'

volumes:
  postgres-data:
  cassandra-data:

networks: 
  app-tier-compose-network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: "postgres"
    #hostname: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres-data/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-tier-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: student
    #environment: "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres-data/var/lib/pgadmin4/data
    restart: unless-stopped
    networks:
      - app-tier-compose-network

  cassandra:
    image: 'cassandra:latest'
    container_name: "cassandra"
    ports:
      - "6000:9042"
    expose:
      - "6000"
    volumes:
      - ./cassandra-data/var/lib/cassandra/data
    restart: unless-stopped
    networks:
      - app-tier-compose-network

# One DSE node
  dse:
    image: luketillman/datastax-enterprise:5.1.0
    container_name: dse
    # Tell DSE to start a graph node
    command: [ -g ]
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    # Use the externally created network (see note above)
    networks:
    - app-tier-compose-network
    # Specify the container name explicitly to avoid getting underscores (see note above)
    

  # One instance of DataStax Studio
  studio:
    image: luketillman/datastax-studio:2.0.0
    ports:
    # The Web UI exposed to our host
    - "9091:9091"
    depends_on:
    - dse
    # Use the externally created network (see note above)
    networks:
    - app-tier-compose-network